// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGYuwdqzLM2PXTCw2E6L_9mh00grrR8FM',
    appId: '1:394505151867:web:e3213d0e9a49a25eb4c9de',
    messagingSenderId: '394505151867',
    projectId: 'bookswap-c7bdb',
    authDomain: 'bookswap-c7bdb.firebaseapp.com',
    storageBucket: 'bookswap-c7bdb.firebasestorage.app',
    measurementId: 'G-7XZHKHEYZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ZuYvfhO7As6oZu7ULv6xzu6yiFnuF4k',
    appId: '1:394505151867:android:15932210b24e4c07b4c9de',
    messagingSenderId: '394505151867',
    projectId: 'bookswap-c7bdb',
    storageBucket: 'bookswap-c7bdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrKuKTvajwfaeDas8i-iYfTNTtJzATK7g',
    appId: '1:394505151867:ios:b7c2c8158df003dfb4c9de',
    messagingSenderId: '394505151867',
    projectId: 'bookswap-c7bdb',
    storageBucket: 'bookswap-c7bdb.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrKuKTvajwfaeDas8i-iYfTNTtJzATK7g',
    appId: '1:394505151867:ios:b7c2c8158df003dfb4c9de',
    messagingSenderId: '394505151867',
    projectId: 'bookswap-c7bdb',
    storageBucket: 'bookswap-c7bdb.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGYuwdqzLM2PXTCw2E6L_9mh00grrR8FM',
    appId: '1:394505151867:web:89982a29a03aaa4db4c9de',
    messagingSenderId: '394505151867',
    projectId: 'bookswap-c7bdb',
    authDomain: 'bookswap-c7bdb.firebaseapp.com',
    storageBucket: 'bookswap-c7bdb.firebasestorage.app',
    measurementId: 'G-D3R2KEGRGB',
  );
}
