// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_ddjmukGA3D9IG6zQd_QvFC0gep5ljVw',
    appId: '1:270102586366:web:bf92f198d85f33001a96af',
    messagingSenderId: '270102586366',
    projectId: 'bookswap-cf2f2',
    authDomain: 'bookswap-cf2f2.firebaseapp.com',
    storageBucket: 'bookswap-cf2f2.firebasestorage.app',
    measurementId: 'G-6B5L296LYT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDF9Cr-y8V1aXEey2wrevpdVZR13IQiA74',
    appId: '1:270102586366:android:a8e9c2e40fc4f5ca1a96af',
    messagingSenderId: '270102586366',
    projectId: 'bookswap-cf2f2',
    storageBucket: 'bookswap-cf2f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARItuaAh4hl637YziBQWX-1DYABKb9koo',
    appId: '1:270102586366:ios:40e34f8b0a5d97b11a96af',
    messagingSenderId: '270102586366',
    projectId: 'bookswap-cf2f2',
    storageBucket: 'bookswap-cf2f2.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARItuaAh4hl637YziBQWX-1DYABKb9koo',
    appId: '1:270102586366:ios:40e34f8b0a5d97b11a96af',
    messagingSenderId: '270102586366',
    projectId: 'bookswap-cf2f2',
    storageBucket: 'bookswap-cf2f2.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_ddjmukGA3D9IG6zQd_QvFC0gep5ljVw',
    appId: '1:270102586366:web:4df56cf5835b1a2e1a96af',
    messagingSenderId: '270102586366',
    projectId: 'bookswap-cf2f2',
    authDomain: 'bookswap-cf2f2.firebaseapp.com',
    storageBucket: 'bookswap-cf2f2.firebasestorage.app',
    measurementId: 'G-VKH26F21TD',
  );

}